canary:
  enable: true
  loadtest_url: http://flagger-loadtester.flagger-system/ # <flagger-service>.<namespace>
  namespace:
ingress:
  host: app.992382555771.realhandsonlabs.net
  name: nestjs-ingress
  paths:
    - backend:
        path: /
        service:
          name: nestjs-service
          port_number: 80
nestjs:
  deployment:
    name: nestjs-app
    image: oussamabal/devops-project:27db8c9c
    replicas: 5
    port: 3000
    variables:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - DB_SYNCHRONIZE
  secret:
    name: nestjs-secret
    data:
      DB_HOST: postgres-app-0.postgres-service.production.svc.cluster.local #<pod-name>.<headless-service-name>.<namespace>.svc.cluster.local
      DB_PORT: "5432"
      DB_USERNAME: oussama
      DB_PASSWORD: oussama
      DB_NAME: oussama
      DB_SYNCHRONIZE: "true"
  service:
    name: nestjs-service
    type: ClusterIP
    port: 80
    target_port: 3000
postgres:
  statefulset:
    name: postgres-app
    image: postgres:latest
    replicas: 1
    port: 5432
    variables:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA
    sidecar:
      name: postgres-exporter
      image: prometheuscommunity/postgres-exporter
      port: 9187
      target_port: 9187
  pvc:
    name: postgres-pvc
    storage: 10Gi
    storageclass: gp2
  secret:
    name: postgres-secret
    data:
      POSTGRES_USER: "oussama"
      POSTGRES_PASSWORD: "oussama"
      POSTGRES_DB: "oussama"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  service:
    name: postgres-service
    port: 5432
    target_port: 5432
