apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nestjs-app
  namespace: production
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nestjs-app
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: nestjs-ingress
  progressDeadlineSeconds: 60
  service:
    port: 80
    targetPort: 3000
  analysis:
    interval: 15s
    threshold: 10
    maxWeight: 80
    stepWeight: 20
    metrics:
    - name: error-rate
      templateRef:
        name: error-rate
        namespace: production
      thresholdRange:
        max: 1
      interval: 30s
    webhooks:
    - name: load-test
      url: {{ .Values.canary.loadtest_url }}
      timeout: 5s
      metadata:
        cmd: "hey -z 1m -q 6 -c 2 https://{{ .Values.ingress.host }}"
