apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: production
  annotations:
    external-dns.alpha.kubernetes.io/hostname: help.851725342659.realhandsonlabs.net
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - help.851725342659.realhandsonlabs.net
    secretName: tls-secret
  rules:
  - host: help.851725342659.realhandsonlabs.net
    http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ .backend.path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .backend.service.name | quote}}
            port:
              number: {{ .backend.service.port_number }}
      {{- end}}

