apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    app: postgres
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app: {{ .Values.postgres.deployment.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.target_port }}
    
  - name: metrics
    port: 9187
    targetPort: 9187
