apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple Pods to read/write
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storage }}
  storageClassName: {{ .Values.postgres.pvc.storage_class }}
