apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels:
    app: postgres
spec:
  clusterIP: None  # Required for stable network ID in StatefulSet
  selector:
    app: {{ .Values.postgres.statefulset.name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.target_port }}
  - name: metrics
    port: {{ .Values.postgres.statefulset.sidecar.port }}
    targetPort: {{ .Values.postgres.statefulset.sidecar.target_port }}